String marshalling fix
Speykious/NativeFileDialogs.NET pull request #3
Opened 2023-12-09 08:22 UTC by ds5678

Hello again. I solved the issue I reported in #2. It was caused by native not being Utf8 on all platforms. I bumped CppSharp to the latest version and ran it on the header for Native File Dialog Extended `v1.1.1`.

2023-12-09 08:26 UTC, Speykious commented on NativeFileDialogs.AutoGen/Std.cs
> +#pragma warning disable CS0109 // Member does not hide an inherited member; new keyword is not required
Was that generated by CppSharp?

2023-12-09 08:36 UTC, Speykious commented
Awesome! Gonna check that everything still works on my machine and stuff

2023-12-09 08:58 UTC, Speykious requested changes
I'd gladly accept this change, especially if it means making sure we're using utf-8.
But unfortunately, that change is not gonna work on Linux (and fwiw, on Mac too). :(
On non-Windows platforms, since the native charset is already utf-8, in nativefiledialog-extended, they're defined as a C macro:
https://github.com/Speykious/nativefiledialog-extended/blob/ab1e78eb5462f153d247bad309760d0bd67a6d57/src/include/nfd.h#L266-L273

I think I (or you?)'ll need to slightly modify the CppSharpGenerator so that it changes the names of the functions on non-Windows platforms.

2023-12-09 09:24 UTC, ds5678 commented
If you know how to fix it, go right ahead. You should have push access to my branch.

Otherwise, I'll take a look tomorrow.

2023-12-09 09:28 UTC, Speykious commented
So far I've tried a somewhat naive approach of adding function name replacements (`N` to `U8`) in the `PostProcess` method, and I think it seemed to work up until it was time to find the `nfdu8filteritem_t` type. I think CppSharp can't find it yet again because it's a `#define`, but I can't find a function to rename that type...

2023-12-09 14:23 UTC, ds5678 commented
I think the best solution might be to ask the native library author to make the API universal. A few small tweaks upstream and generating interop bindings becomes easier for all frameworks.

2023-12-09 14:34 UTC, ds5678 commented
If we pr that change upstream, the utf8 methods will work out of the box on all 3 platforms. 

However, the native methods will have cross platform differences. Currently, the CppSharp output code aligns with Windows wide characters. I propose we add `SupportedOSPlatform` attributes to the native methods. That would warn developers that they should only use the native methods on Windows.

2023-12-09 18:02 UTC, ds5678 commented
https://github.com/btzy/nativefiledialog-extended/pull/118

2023-12-09 18:04 UTC, ds5678 commented
https://github.com/AssetRipper/nativefiledialog-extended/actions/runs/7152679491

2023-12-09 19:32 UTC, Speykious commented
Well that was fast :v

2023-12-09 19:48 UTC, ds5678 commented
I also want to pr doxygen support to the native library because that will let CppSharp pull the documentation for our library.

2023-12-09 19:55 UTC, ds5678 commented
I also asked about injecting attributes.

https://github.com/mono/CppSharp/discussions/1804

2023-12-12 16:40 UTC, ds5678 commented
> I also asked about injecting attributes.
> 
> [mono/CppSharp#1804](https://github.com/mono/CppSharp/discussions/1804)

I was able to inject the attributes!

2023-12-23 21:16 UTC, ds5678 commented
A few updates:

* My upstream changes were merged!
* I set up automated building. https://github.com/AssetRipper/nativefiledialog-extended-builds/actions

2023-12-25 13:35 UTC, Speykious commented
Oh my god... I didn't have any Readme file all this time?? This is bad :skull:

2023-12-25 14:08 UTC, Speykious commented
I'll update `NativeFileDialogs.Net.Runtime` now

2023-12-25 14:23 UTC, ds5678 commented
Much appreciated

2023-12-25 14:48 UTC, Speykious commented
> If you know how to fix it, go right ahead. You should have push access to my branch.
> 
> Otherwise, I'll take a look tomorrow.

Well... apparently I don't! D:

```
❯ git push AssetRipper HEAD:string-marshalling-fix
ERROR: Permission to AssetRipper/NativeFileDialogs.NET.git denied to Speykious.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

2023-12-25 14:52 UTC, ds5678 commented
What were you trying to change? Just bumping the NuGet version?

2023-12-25 14:57 UTC, Speykious commented
Yes, on all packages for `NativeFileDialogs.Runtime`, and also change the submodule since we don't need my fork anymore.
![image](https://github.com/Speykious/NativeFileDialogs.NET/assets/13885008/9bfba16c-c571-43c3-bede-f96cbba136b5)

2023-12-25 15:11 UTC, ds5678 commented
I don't think you can push to my branch, probably because I made this from an organization repository.

![brave_2023-12-25_10-08-00](https://github.com/Speykious/NativeFileDialogs.NET/assets/49847914/688feced-a2fb-4e7e-8f63-fbbc937892f1) ![brave_2023-12-25_10-09-27](https://github.com/Speykious/NativeFileDialogs.NET/assets/49847914/ac25403a-fed9-430b-ac8e-a32b6e415be7)

2023-12-25 15:13 UTC, Speykious commented
I see. Is there anything you can do in the organization itself then?

2023-12-25 15:17 UTC, ds5678 commented
I added permissions for you to push to that repository, so you should be good now.

2023-12-25 15:20 UTC, Speykious commented
Thanks, it worked :D

2023-12-25 15:25 UTC, Speykious commented
The examples work on my end with the new versions! I'll do one more test before merging.

2023-12-25 15:36 UTC, ds5678 commented
I noticed that you were referencing the Autogen NuGet package. It's only necessary to reference the Runtime NuGet package due to how native libraries are used.

2023-12-25 15:41 UTC, Speykious commented
Oh damn, it has actually never worked on Mac. I'm getting a `DllNotFoundException`. It can't find the `libnfd.dylib` in the right place no matter what name I give the `runtimes/osx-...` directory. I guess that's a separate issue I'll have to pull up.

2023-12-25 15:43 UTC, Speykious commented
> I noticed that you were referencing the Autogen NuGet package. It's only necessary to reference the Runtime NuGet package due to how native libraries are used.

What do you mean? As in I should turn AutoGen into a project reference instead?

2023-12-25 15:43 UTC, Speykious approved these changes

2023-12-25 15:47 UTC, ds5678 commented
https://github.com/Speykious/NativeFileDialogs.NET/pull/3/commits/613358ec52f5ddebaf6474fcd3a7c20518c3f530

2023-12-25 15:51 UTC, ds5678 commented
Whenever you compile, all the NuGet references will be correct in the generated packages.

2023-12-25 15:52 UTC, Speykious commented
Ah right. Yeah that's what you meant. That's fine

2023-12-25 15:55 UTC, merged